InventoryUI/Controllers/ItemsController.cs
using Inventory.Core.Model;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;

using System.Web.Mvc;

namespace InventoryUI.Controllers
{
    public class ItemsController : Controller
    {

        string ApiPath = System.Configuration.ConfigurationManager.AppSettings["ApiPath"];


        public ActionResult Index(int? id)
        {
            ViewBag.category = getCategory(); 
            //var includes = new Includes<Item>(query =>
            //{
            //    return query.Include(b => b.Category)
            //                    .Include(a => a.Contact);
            //});
            Item curItem=new Item() { ItemCode="0"};
           
            //var curItem = ItemRepositry.Include(a=>a.Contact).Where(a=>a.ItemID==id).FirstOrDefault();
            //if (id.HasValue)
            //curItem= ItemRepositry.FindBy(a => a.ItemID ==id.Value, null, includes.Expression).FirstOrDefault(a=>a.isActive);
            //if (TempData["CurItem"] != null)
            //    curItem =(Item) TempData["CurItem"];
            return View(curItem);
        }
        public async Task<ActionResult>  GetGridDetails(bool AllData)
        {
            List<Item> itemList = null;
            int itemNo = AllData == true ? 200000 : 30;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(ApiPath);

                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage responseMessage = await client.GetAsync("/Category/GetAll?takeNo=" + itemNo.ToString());
            
            if (responseMessage.IsSuccessStatusCode)
            {
                //Storing the response details recieved from web api   
                var Response = responseMessage.Content.ReadAsStringAsync().Result;

                //Deserializing the response recieved from web api and storing into the Employee list  
                itemList = JsonConvert.DeserializeObject<List<Item>>(Response);

            }
            }
            return PartialView(itemList);
        }


        private async Task<List<Category>> getCategory()
        {

            if (HttpContext.Application["CategoryLst"] != null)
            {
                return ( List<Category>)HttpContext.Application["CategoryLst"];

            }

           
            using (var client = new HttpClient())
            {
                //setup client
                client.BaseAddress = new Uri(ApiPath);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                List<Category> CategoryLst = null;


                HttpResponseMessage responseMessage = await client.GetAsync("/Category/GetAll");

                if (responseMessage.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var Response = responseMessage.Content.ReadAsStringAsync().Result;

                    //Deserializing the response recieved from web api and storing into the Employee list  
                    CategoryLst = JsonConvert.DeserializeObject<List<Category>>(Response);

                }

                return CategoryLst;


            }
        }

        //public ActionResult GetGridDetails(bool AllData)
        //{
        //    var includes = new Includes<Item>(query =>
        //    {
        //        return query.Include(b => b.Category)
        //                        .Include(a => a.Contact);
        //    });

        //    List<Item> itemList = null;
        //    if (AllData == true)
        //        itemList = ItemRepositry.FindBy(a => a.isActive,null, includes.Expression).OrderByDescending(b => b.ItemID).ToList();
        //    else
        //        itemList = ItemRepositry.FindBy(a => a.isActive,null, includes.Expression).OrderByDescending(b => b.ItemID).Take(20).ToList(); 

        //    return PartialView(itemList);
        //}



        //public int Delete(int id)
        //{
        //    var curItem = ItemRepositry.FindBy(s => s.ItemID == id).FirstOrDefault();
        //    curItem.isActive = false;
        //    ItemRepositry.Update(curItem);
        //    return 1;


        //}
        //[HttpPost]
        //public ActionResult Save(Item CurItem)
        //{
        //    CurItem.Contact = null;

        //    if (ModelState.IsValid)
        //    {

        //        if (CurItem.ItemID == 0)
        //        {
        //            CurItem.isActive = true;
        //            int c =ItemRepositry.FindBy(a => a.ItemName == CurItem.ItemName).Count();
        //            if (c != 0)
        //            {
        //                TempData["CurItem"] = CurItem;
        //                TempData["error"] = "هذا الاسم موجود من قبل";
        //                return RedirectToAction("Index");
        //            }
        //             c = ItemRepositry.FindBy(a => a.ItemCode == CurItem.ItemCode).Count();
        //            if (c != 0)
        //            {
        //                TempData["CurItem"] = CurItem;
        //                TempData["error"] = "هذا الكود موجود من قبل";
        //                return RedirectToAction("Index");
        //            }
        //        }

        //        if (CurItem.ItemID == 0)
        //            CurItem.isActive = true;
        //        //CurItem.CategoryID = 1;
        //        if( CurItem.ItemCode=="0")
        //            CurItem.ItemCode=GenerateItemCode();
        //        CurItem.CreationDate = DateTime.Now;
        //        CurItem.CreatedBy = (int)Session["UserId"];
        //        ItemRepositry.Save(CurItem);
        //    }
        //    else
        //    { var errors = ModelState.Values.SelectMany(vd => vd.Errors); }

        //   return RedirectToAction("Index");
        //}

        //private string GenerateItemCode()
        //{
        //  return(  (ItemRepositry.GetAll().ToList().Max(a => decimal.Parse(a.ItemCode))+1).ToString());
        //}

        //[HttpPost]
        //public JsonResult AutoCompleteItemName(string prefix)
        //{
        //    var itemList = ItemRepositry.FindBy(a=>a.isActive).ToList();
        //    if (prefix != "*")
        //        itemList = ItemRepositry.FindBy(a => a.ItemName.Contains(prefix) == true).OrderBy(s => s.ItemCode).ToList();

        //    return Json(itemList.Select(a => new
        //    {
        //        label = a.ItemName,
        //        val = a.ItemID
        //    }), JsonRequestBehavior.AllowGet);
        //}
        //[HttpPost]
        //public JsonResult AutoCompleteItemCode(string prefix)
        //{
        //    var itemList = ItemRepositry.FindBy(a => a.isActive).ToList();
        //    if (prefix != "*")
        //        itemList = ItemRepositry.FindBy(a => a.ItemCode.StartsWith(prefix) == true).OrderBy(s=>s.ItemCode).ToList();

        //    return Json(itemList.Select(a => new
        //    {
        //        label = a.ItemName,
        //        val = a.ItemID
        //    }), JsonRequestBehavior.AllowGet);
        //}

        //[HttpPost]
        //public JsonResult GetItemData(string ItemCode,string ItemID)
        //{
        //    dynamic itemList ;
        //    if (ItemCode != "")
        //        itemList = ItemRepositry.FindBy(a => a.ItemCode == ItemCode).FirstOrDefault();
        //    else
        //        itemList = ItemRepositry.FindBy(a => a.ItemID == int.Parse(ItemID)).FirstOrDefault();
        //    return Json(itemList, JsonRequestBehavior.AllowGet);
        //}
    }
}

InventoryUI/Views/Items/Index.cshtml
@model Inventory.Core.Model.Item
@*@using System.Reflection
    @using SalesTaxMVC.ViewModel*@
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<style>
    .box.box-primary {
        border-top-color: #3c8dbc;
    }

    .box-body {
        border-top-left-radius: 0;
        border-top-right-radius: 0;
        border-bottom-right-radius: 3px;
        border-bottom-left-radius: 3px;
        padding: 10px;
    }

    .box {
        position: relative;
        border-radius: 3px;
        background: #ffffff;
        border-top: 3px solid #d2d6de;
        margin-bottom: 20px;
        width: 100%;
        box-shadow: 0 1px 1px rgba(0,0,0,0.1);
    }

    .form-control {
        direction: rtl;
    }

    .box-header {
        color: #444;
        display: block;
        padding: 10px;
        position: relative;
    }

    input[type="text"] {
        direction: rtl;
        text-align: right;
    }

    .box-header.with-border {
        border-bottom: 1px solid #f4f4f4;
    }

    .form {
        margin: 0em 1em;
    }

    form {
        width: 100%;
    }

    .content {
        direction: rtl;
        text-align: right;
    }


    .dropdown-toggle {
        border: 0 !important;
        background-image: linear-gradient(0deg,#9c27b0 2px,rgba(156,39,176,0) 0),linear-gradient(0deg,#d2d2d2 1px,hsla(0,0%,82%,0) 0);
        background-size: 0 100%,100% 100%;
        background-repeat: no-repeat;
        background-position: bottom,50% calc(100% - 1px);
        background-color: transparent !important;
        transition: background 0s linear !important;
        float: none !important;
        box-shadow: none !important;
        border-radius: 0 !important;
        color: #3c4858 !important;
        height: 34px;
        padding-left: 0 !important;
        padding-bottom: 5px !important;
    }
</style>




@using (Html.BeginForm("Save", "Items"))
{


    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">ادخال وتعديل الصنف</h3>
        </div><!-- /.box-header -->
        <!-- form start -->
        <div class="form">
            <div class="box-body">
                @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    <font color="red">@((String)TempData["error"])</font>
                    @Html.HiddenFor(m => m.ItemID)
                    <div class="row">
                        <div class="col-md-2">
                            <div class="form-group">
                                @Html.LabelFor(model => model.ItemName)
                                @Html.HiddenFor(model => model.isActive)
                                @Html.EditorFor(model => model.ItemName, new { htmlAttributes = new { @class = "form-control", @required = "true" } })
                                @Html.ValidationMessageFor(model => model.ItemName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                @Html.LabelFor(model => model.ItemCode)
                                @Html.EditorFor(model => model.ItemCode, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ItemCode, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        @*<div class="col-md-3">
                                <div class="form-group">


                                    @Html.DropDownListFor(model => model.CategoryID, new SelectList(@ViewBag.category, "ItemCategoryID", "CategoryName"), new { @class = "selectpicker", title = "نوع الصنف" })
                                </div>
                            </div>*@
                        <div class="col-md-2">
                            <div class="form-group">
                                <label> المورد</label>
                                @Html.HiddenFor(model => model.SupplierID)
                                @*@Html.HiddenFor(model => model.Contact.ContactTypeID)*@
                                @Html.TextBoxFor(model => model.Contact.ContactName, new { @class = "form-control AutoCompleteContact", @required = "true" })
                            </div>
                        </div>

                        <div class="col-md-2">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control", @required = "true" } })
                                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Price)
                                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @required = "true" } })
                                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                @Html.LabelFor(model => model.MinLimit)
                                @Html.EditorFor(model => model.MinLimit, new { htmlAttributes = new { @class = "form-control" } })

                            </div>
                        </div>
                        <div class="col-md-2">

                            @Html.DropDownListFor(model => model.CategoryID, new SelectList(@ViewBag.Category, "ItemCategoryID", "CategoryName"), new { @class = "selectpicker" })

                        </div>
                        <div class="col-md-2">
                            <div class="box-footer" style="padding: 20px">
                                <input type="submit" value="ادخال" class="btn btn-default pull-right" />
                            </div>
                        </div>
                    </div><!-- /.box-body -->
                </div>
            </div>
        </div>
    </div>
}






<div class="row">
    <label><input id="CkGetAllData" type="checkbox" value="">عرض كل البيانات</label>
</div>

<div id="Detailss">
    @*@Html.Partial("GetBSBDetails", new List<VMBsbDetails>());*@

</div>



<script type="text/javascript">
    $("document").ready(function () {
        //$('#CkGetAllData').prop("Checked","");




        showDetails();


        $('#CkGetAllData').change(showDetails);



        function showDetails() {
            var chVal = $('#CkGetAllData').is(':checked');
            $.ajax({
                url: '@Url.Action("GetGridDetails", "Items")',
                data: { 'AllData': chVal },

                cache: false,
                method: 'GET',
                success: function (data) { $("#Detailss").text(''); $("#Detailss").html(data); },
                error: function (xhr) {
                    alert('Request Status: ' + xhr.status + ' Status Text: ' + xhr.statusText + ' ' + xhr.responseText);
                }
            });

        }





    });


    $(function () {

        $(".AutoCompleteContact").autocomplete({

            source: function (request, response) {
                $.ajax({
                    url: '@Url.Action("AutoCompleteContact", "Contact")',
                    data: "{'prefix':'" + request.term + "', 'ContactCategoryID':" + 2 + "}",
                    //data: "{ 'prefix': '" + request.term + "',ParentID:" + $("#ItemID option:selected").val() + "}",
                    dataType: "json",
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        response($.map(data, function (item) {
                            return item;
                        }))
                    },
                    error: function (response) {
                        alert(response.responseText);
                    },
                    failure: function (response) {
                        alert(response.responseText);
                    }
                });
            },
            select: function (e, i) {
                $("#SupplierID").val(i.item.val);

            },
            minLength: 1
        });
    })
</script>